#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 2.4.{build}.0
image: Visual Studio 2015
install:
    - git clone https://github.com/johlju/DscResource.Tests
    - ps: Push-Location
    - ps: cd "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests"
    - git checkout fix-pscore
    - ps: Pop-Location
    - ps: Write-Verbose -Message "Returned after restart with PSVersion $($PSVersionTable.PSVersion)" -Verbose
    - ps: if ($PSVersionTable.PSVersion -lt [Version] '5.1')
        {
            throw 'WMF 5.1 install failed'
        }
    - ps: Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
    - ps: Invoke-AppveyorInstallTask

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
- pwsh: Install-Module -Name Pester
- pwsh: |
    Write-Verbose -Message "Tests are running in PSVersion $($PSVersionTable.PSVersion)" -Verbose
    Write-Verbose -Message "Project folder is: $($env:APPVEYOR_BUILD_FOLDER)" -Verbose
    Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
    Get-Module | % { Write-Verbose "Loaded module: $($_.Name)" -Verbose }
    Get-Command -Module AppVeyor | % { Write-Verbose "Command: $($_.Name)" -Verbose }
    Invoke-AppveyorTestScriptTask -CodeCoverage -CodeCovIo
#- ps: Add-AppveyorTest -Name "Windows PowerShell" -Framework NUnit -Filename pwsh.exe -Outcome Passed -Duration 1000
#- pwsh: |
#    Add-AppveyorTest -Name "PowerShell Core" -Framework NUnit -Filename pwsh.exe -Outcome Passed -Duration 1000

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
    - ps: |
        Invoke-AppveyorAfterTestTask
