#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 2.4.{build}.0
install:
    - git clone https://github.com/SSvilen/DscResource.Tests
    - ps: Push-Location
    - ps: cd "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests"
    - git checkout KeywordsCheck
    - ps: Pop-Location
    - ps: |
        $moduleName = 'PSDscResources'
        Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -Type 'Default' `
            -CodeCoverage `
            -CodeCovIo `
            -DisableConsistency `
            -ExcludeTag @()

after_test:
  - ps: |
        Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorAfterTestTask `
            -ResourceModuleName $moduleName

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy_script:
    - ps: |
        Invoke-AppveyorAfterTestTask
